--liquibase formatted sql

--changeset dgaraev:new tables

  create table cats(
id bigint generated by default as identity primary key,
name text,
breed text,
color text
 );

  create table dogs(
id bigint generated by default as identity primary key,
name text,
breed text,
color text
 );

  create table cat_adopters(
id bigint generated by default as identity primary key,
name text,
phone text,
dog_id bigint references cats(id)
 );

  create table dog_adopters(
id bigint generated by default as identity primary key,
name text,
phone text,
dog_id bigint references dogs(id)
 );

  create table report_about_cats(
id bigint generated by default as identity primary key,
photo bytea,
ration text,
habits text,
behavior text,
lastMessage date,
cat_adopter_id bigint references cat_adopters(id)
 );

  create table report_about_dogs(
id bigint generated by default as identity primary key,
photo bytea,
ration text,
habits text,
behavior text,
lastMessage date,
dog_adopter_id bigint references dog_adopters(id)
 );

  create table volunteers(
id bigint generated by default as identity primary key,
name text,
phone text,
userName text
 );





